# Generated by Django 5.1.3 on 2024-12-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rewardcode_alter_userprofile_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='point_accumulated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
