# Generated by Django 5.1.3 on 2024-12-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points_awarded_for_email',
            field=models.BooleanField(default=False),
        ),
    ]
